### ISSUE TITLE
Handle "candidate release" version 

### ISSUE THREAD

**Issue by brettwooldridge** [versioneye/naturalsorter#10]
See comments here: https://www.versioneye.com/vc/5887018501b8e60016497a58?utm_medium=email&utm_source=version_comment_reply

Some projects publish "release candidates", which while appearing to be a newer version, as they are not official should not be considered newer than the stable release.

For example, "3.22.0-CR1" is less than "3.21.0-GA".

Common suffix include "RC", "CR", "Alpha", "Beta" ... sometimes followed by a digit.

hibernate-search examples: 4.3.0.Alpha1, 5.6.0.Beta2

At the same time, there are suffix like "Final" and "GA". 

Actually, if you go to http://search.maven.org and enter *just* "hibernate", the first two pages of results will show you just about all the variety necessary.

**Comment by brettwooldridge** [comment]
Specifically, these tests should probably pass:
```ruby
  it "3.21.0-GA is bigger than 3.21.0-Beta3" do
    expect( Versioncmp.compare("3.21.0-GA", "3.21.0-Beta3")).to eql(1)
  end

  it "3.21.0-GA is bigger than 3.22.0-CR1" do
    expect( Versioncmp.compare("3.21.0-GA", "3.22.0-CR1")).to eql(1)
  end
```

**Comment by reiz** [comment]
Hi @brettwooldridge Wit this [commit](https://github.com/versioneye/naturalsorter/commit/e273a0341ebfc85f369fbdca8e21244c5dff61bc) I added support cor CR versions. As far as I can see CR is the same as RC. That should fix the issue. 

`3.21.0-GA` is not bigger than `3.22.0-CR1`! Clearly `3.22.0-CR1` is newer, but it's not considered as stable release. VersionEye is recognising stable releases and for the newest version we only take stable releases. 

I close this ticket because the issue CR and RC should be fixed. Please update your project on VersionEye and let me know if it works like expected. If the issue still exist please reopen this ticket.
